---
- name: Ensure UFW is Started and Enabled
  systemd:
    name: ufw
    state: started
    enabled: true

- name: Configure ufw for Splunk
  become: true
  ufw:
    port: "{{ item }}"
    proto: tcp
    rule: allow
  loop: "{{ splunk_firewall_ports }}"
