---
- name: Ensure Firewalld is Started and Enabled
  systemd:
    name: firewalld
    state: started
    enabled: true

- name: Configure firewalld for Splunk
  become: true
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ splunk_firewall_ports }}"
